### ISSUE TITLE
Too many 500 error responses

### ISSUE THREAD

**Issue by davidw3591** [homeylab/bookstack-file-exporter#43]
I installed your tool but running into an issue. When it starts to export it trows an error: **Too many 500 error responses**
I just have 1 user in bookstack.

Did I configure something wrong?

**config.yml:**
```
host: "http://bookstack.mynet/"
credentials:
    token_id: "<redacted>"
    token_secret: "<redacted>"
formats:
  - pdf
assets:
  export_images: false
  export_attachments: false
  modify_markdown: false
  export_meta: false
  verify_ssl: false
output_path: "/export/dump"
keep_last: 5
```

**Docker logs:**
```
2024-09-09 08:27:49 [INFO] Beginning run
2024-09-09 08:27:49 [INFO] Building shelve/book/chapter/page relationships
2024-09-09 08:27:49 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:49 [DEBUG] http://bookstack.mynet:80 "GET /api/shelves HTTP/11" 200 None
2024-09-09 08:27:49 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:50 [DEBUG] http://bookstack.mynet:80 "GET /api/shelves/1 HTTP/11" 200 None
2024-09-09 08:27:50 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:50 [DEBUG] http://bookstack.mynet:80 "GET /api/shelves/2 HTTP/11" 200 None
2024-09-09 08:27:50 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:51 [DEBUG] http://bookstack.mynet:80 "GET /api/books/1 HTTP/11" 200 None
2024-09-09 08:27:51 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:51 [DEBUG] http://bookstack.mynet:80 "GET /api/books HTTP/11" 200 None
2024-09-09 08:27:51 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:52 [DEBUG] http://bookstack.mynet:80 "GET /api/books/2 HTTP/11" 200 None
2024-09-09 08:27:52 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:52 [DEBUG] http://bookstack.mynet:80 "GET /api/books/3 HTTP/11" 200 None
2024-09-09 08:27:52 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:53 [DEBUG] http://bookstack.mynet:80 "GET /api/books/4 HTTP/11" 200 None
2024-09-09 08:27:53 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:53 [DEBUG] http://bookstack.mynet:80 "GET /api/books/5 HTTP/11" 200 None
2024-09-09 08:27:53 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:54 [DEBUG] http://bookstack.mynet:80 "GET /api/books/6 HTTP/11" 200 None
2024-09-09 08:27:54 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:54 [DEBUG] http://bookstack.mynet:80 "GET /api/books/7 HTTP/11" 200 None
2024-09-09 08:27:54 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:55 [DEBUG] http://bookstack.mynet:80 "GET /api/books/8 HTTP/11" 200 None
2024-09-09 08:27:55 [DEBUG] Book Node child of type: chapter is not desired type: page
2024-09-09 08:27:55 [DEBUG] Book Node child of type: chapter is not desired type: page
2024-09-09 08:27:55 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:55 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/7 HTTP/11" 200 None
2024-09-09 08:27:55 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:55 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/10 HTTP/11" 200 None
2024-09-09 08:27:56 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:56 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/11 HTTP/11" 200 None
2024-09-09 08:27:56 [DEBUG] Book Node child of type: chapter is not desired type: page
2024-09-09 08:27:56 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:56 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/14 HTTP/11" 200 None
2024-09-09 08:27:56 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:57 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/15 HTTP/11" 200 None
2024-09-09 08:27:57 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:57 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/18 HTTP/11" 200 None
2024-09-09 08:27:57 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:58 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/19 HTTP/11" 200 None
2024-09-09 08:27:58 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:58 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/20 HTTP/11" 200 None
2024-09-09 08:27:58 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:59 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/21 HTTP/11" 200 None
2024-09-09 08:27:59 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:27:59 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/22 HTTP/11" 200 None
2024-09-09 08:27:59 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:00 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/29 HTTP/11" 200 None
2024-09-09 08:28:00 [DEBUG] Book Node child of type: chapter is not desired type: page
2024-09-09 08:28:00 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:00 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/30 HTTP/11" 200 None
2024-09-09 08:28:00 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:00 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/31 HTTP/11" 200 None
2024-09-09 08:28:00 [DEBUG] Book Node child of type: chapter is not desired type: page
2024-09-09 08:28:00 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:01 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters HTTP/11" 200 None
2024-09-09 08:28:01 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:01 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters/2 HTTP/11" 200 None
2024-09-09 08:28:01 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:02 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters/3 HTTP/11" 200 None
2024-09-09 08:28:02 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:02 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters/4 HTTP/11" 200 None
2024-09-09 08:28:02 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:03 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters/5 HTTP/11" 200 None
2024-09-09 08:28:03 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:03 [DEBUG] http://bookstack.mynet:80 "GET /api/chapters/6 HTTP/11" 200 None
2024-09-09 08:28:03 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:04 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/1 HTTP/11" 200 None
2024-09-09 08:28:04 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:04 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/3 HTTP/11" 200 None
2024-09-09 08:28:04 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:05 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/2 HTTP/11" 200 None
2024-09-09 08:28:05 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:05 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/4 HTTP/11" 200 None
2024-09-09 08:28:05 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:05 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/5 HTTP/11" 200 None
2024-09-09 08:28:05 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:06 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/17 HTTP/11" 200 None
2024-09-09 08:28:06 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:06 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/12 HTTP/11" 200 None
2024-09-09 08:28:06 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:07 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/13 HTTP/11" 200 None
2024-09-09 08:28:07 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:07 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/16 HTTP/11" 200 None
2024-09-09 08:28:07 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:08 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/23 HTTP/11" 200 None
2024-09-09 08:28:08 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:08 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/24 HTTP/11" 200 None
2024-09-09 08:28:08 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:09 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/25 HTTP/11" 200 None
2024-09-09 08:28:09 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:09 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/26 HTTP/11" 200 None
2024-09-09 08:28:09 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:10 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/27 HTTP/11" 200 None
2024-09-09 08:28:10 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:10 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/28 HTTP/11" 200 None
2024-09-09 08:28:10 [INFO] Beginning archive
2024-09-09 08:28:10 [INFO] Exporting all bookstack page contents
2024-09-09 08:28:10 [DEBUG] Starting new HTTP connection (1): bookstack.mynet:80
2024-09-09 08:28:11 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/7/export/pdf HTTP/11" 500 None
2024-09-09 08:28:11 [DEBUG] Incremented Retry for (url='/api/pages/7/export/pdf'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2024-09-09 08:28:11 [DEBUG] Retry: /api/pages/7/export/pdf
2024-09-09 08:28:12 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/7/export/pdf HTTP/11" 500 None
2024-09-09 08:28:12 [DEBUG] Incremented Retry for (url='/api/pages/7/export/pdf'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2024-09-09 08:28:13 [DEBUG] Retry: /api/pages/7/export/pdf
2024-09-09 08:28:14 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/7/export/pdf HTTP/11" 500 None
2024-09-09 08:28:14 [DEBUG] Incremented Retry for (url='/api/pages/7/export/pdf'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2024-09-09 08:28:16 [DEBUG] Retry: /api/pages/7/export/pdf
2024-09-09 08:28:17 [DEBUG] http://bookstack.mynet:80 "GET /api/pages/7/export/pdf HTTP/11" 500 None
2024-09-09 08:28:17 [ERROR] Failed to make request for http://bookstack.mynet//api/pages/7/export/pdf
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='bookstack.mynet', port=80): Max retries exceeded with url: /api/pages/7/export/pdf (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/export/bookstack_file_exporter/__main__.py", line 16, in <module>
    main()
  File "/export/bookstack_file_exporter/__main__.py", line 12, in main
    run.exporter(args)
  File "/export/bookstack_file_exporter/run.py", line 45, in exporter
    archive.get_bookstack_exports(page_nodes)
  File "/export/bookstack_file_exporter/archiver/archiver.py", line 43, in get_bookstack_exports
    self._page_archiver.archive_pages(page_nodes)
  File "/export/bookstack_file_exporter/archiver/page_archiver.py", line 74, in archive_pages
    page_data = self._get_page_data(page.id_, export_format)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/bookstack_file_exporter/archiver/page_archiver.py", line 97, in _get_page_data
    return archiver_util.get_byte_response(url=url, headers=self._headers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/bookstack_file_exporter/archiver/util.py", line 17, in get_byte_response
    response = util.http_get_request(url=url, headers=headers, verify_ssl=verify_ssl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/bookstack_file_exporter/common/util.py", line 28, in http_get_request
    raise req_err
  File "/export/bookstack_file_exporter/common/util.py", line 25, in http_get_request
    response = session.get(url, headers=headers, verify=verify_ssl, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='bookstack.mynet', port=80): Max retries exceeded with url: /api/pages/7/export/pdf (Caused by ResponseError('too many 500 error responses'))
```

**Comment by davidw3591** [comment]
When I manually went to the URL http://bookstack.mynet/api/pages/7/export/pdf, I got this error:
`{"error":{"message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 83864236 bytes)","code":500}}`

Then I remembered this is a testpage with a huge DrawIO-diagram on it. After removing this testpage, the script exported everything without further problems.

Thanks for creating this tool! 👍
